# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SendBird-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for SendBird-iOS
  pod 'SendBirdSDK', '~> 3.0'
  pod 'MGSwipeTableCell', :inhibit_warnings => true
  pod 'AFNetworking', :inhibit_warnings => true
  pod 'FLAnimatedImage', '~> 1.0', :inhibit_warnings => true
  pod 'NYTPhotoViewer', '~> 1.1.0', :inhibit_warnings => true
  pod 'HTMLKit', '~> 2.0', :inhibit_warnings => true
  pod 'TTTAttributedLabel', :inhibit_warnings => true
  pod 'RSKImageCropper', :inhibit_warnings => true
end
